"""
Data models and preconfigured team profiles for sports analytics demo & testing.
"""

from typing import Dict, List
from sports_analytics.engine import SportType, TeamStats

# Pre-populated realistic team profiles for demonstration & analysis
TEAM_DATABASE: Dict[str, TeamStats] = {
    # Football
    "Манчестер Сити": TeamStats(
        name="Манчестер Сити",
        played_matches=28,
        wins=20,
        draws=5,
        losses=3,
        goals_or_points_scored=65,
        goals_or_points_conceded=26,
        xg_for=68.5,
        xg_against=24.1,
        form_recent_5=["W", "W", "W", "D", "W"],
        key_injuries_count=0,
        rest_days=6,
        home_advantage_factor=1.20,
    ),
    "Ливерпуль": TeamStats(
        name="Ливерпуль",
        played_matches=28,
        wins=19,
        draws=6,
        losses=3,
        goals_or_points_scored=63,
        goals_or_points_conceded=27,
        xg_for=66.2,
        xg_against=25.8,
        form_recent_5=["W", "W", "W", "W", "D"],
        key_injuries_count=1,
        rest_days=4,
        home_advantage_factor=1.22,
    ),
    "Арсенал": TeamStats(
        name="Арсенал",
        played_matches=28,
        wins=19,
        draws=4,
        losses=5,
        goals_or_points_scored=60,
        goals_or_points_conceded=24,
        xg_for=62.0,
        xg_against=22.5,
        form_recent_5=["W", "W", "L", "W", "W"],
        key_injuries_count=0,
        rest_days=5,
        home_advantage_factor=1.18,
    ),
    "Челси": TeamStats(
        name="Челси",
        played_matches=28,
        wins=13,
        draws=8,
        losses=7,
        goals_or_points_scored=48,
        goals_or_points_conceded=39,
        xg_for=49.1,
        xg_against=38.4,
        form_recent_5=["D", "W", "L", "W", "D"],
        key_injuries_count=2,
        rest_days=3,
        home_advantage_factor=1.12,
    ),
    "Реал Мадрид": TeamStats(
        name="Реал Мадрид",
        played_matches=27,
        wins=20,
        draws=5,
        losses=2,
        goals_or_points_scored=58,
        goals_or_points_conceded=19,
        xg_for=59.4,
        xg_against=21.2,
        form_recent_5=["W", "W", "D", "W", "W"],
        key_injuries_count=1,
        rest_days=4,
        home_advantage_factor=1.25,
    ),
    "Барселона": TeamStats(
        name="Барселона",
        played_matches=27,
        wins=18,
        draws=6,
        losses=3,
        goals_or_points_scored=57,
        goals_or_points_conceded=24,
        xg_for=56.8,
        xg_against=25.0,
        form_recent_5=["W", "W", "W", "D", "W"],
        key_injuries_count=0,
        rest_days=5,
        home_advantage_factor=1.20,
    ),
    # Basketball
    "Бостон Селтикс": TeamStats(
        name="Бостон Селтикс",
        played_matches=55,
        wins=43,
        draws=0,
        losses=12,
        goals_or_points_scored=120.5,
        goals_or_points_conceded=109.8,
        xg_for=121.0,
        xg_against=110.0,
        form_recent_5=["W", "W", "W", "W", "L"],
        key_injuries_count=0,
        rest_days=2,
        home_advantage_factor=1.06,
    ),
    "Денвер Наггетс": TeamStats(
        name="Денвер Наггетс",
        played_matches=55,
        wins=38,
        draws=0,
        losses=17,
        goals_or_points_scored=115.2,
        goals_or_points_conceded=110.1,
        xg_for=116.0,
        xg_against=110.5,
        form_recent_5=["W", "L", "W", "W", "W"],
        key_injuries_count=1,
        rest_days=1,
        home_advantage_factor=1.08,
    ),
    # Tennis Players
    "Янник Синнер": TeamStats(
        name="Янник Синнер",
        played_matches=45,
        wins=40,
        draws=0,
        losses=5,
        goals_or_points_scored=2.4,  # Sets won avg
        goals_or_points_conceded=0.6,
        xg_for=0.88,  # Hold %
        xg_against=0.28,  # Opponent hold % broken
        form_recent_5=["W", "W", "W", "W", "W"],
        key_injuries_count=0,
        rest_days=2,
        home_advantage_factor=1.0,
    ),
    "Карлос Алькарас": TeamStats(
        name="Карлос Алькарас",
        played_matches=42,
        wins=36,
        draws=0,
        losses=6,
        goals_or_points_scored=2.3,
        goals_or_points_conceded=0.7,
        xg_for=0.85,
        xg_against=0.31,
        form_recent_5=["W", "W", "L", "W", "W"],
        key_injuries_count=0,
        rest_days=2,
        home_advantage_factor=1.0,
    ),
    "Даниил Медведев": TeamStats(
        name="Даниил Медведев",
        played_matches=40,
        wins=31,
        draws=0,
        losses=9,
        goals_or_points_scored=2.1,
        goals_or_points_conceded=0.9,
        xg_for=0.82,
        xg_against=0.26,
        form_recent_5=["W", "L", "W", "W", "L"],
        key_injuries_count=0,
        rest_days=1,
        home_advantage_factor=1.0,
    ),
}
